version: "2"
services:
  mongo:
    image: mongo
    volumes:
      - ./cockpit/data:/data/db
      
  cockpit:
    image: agentejo/cockpit:0.10.2
    environment:
      COCKPIT_SESSION_NAME: "cockpit"
      COCKPIT_SALT: "y283y2983y48239y"
      COCKPIT_DATABASE_SERVER: "mongodb://mongo:27017"
      COCKPIT_DATABASE_NAME: "cockpit_master"
    depends_on:
      - mongo
    ports:
      - 8080:80
